// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;

export const modules: ModuleMap = {
  "./components/mockups/landing/AppStyle": () =>
    import("../components/mockups/landing/AppStyle"),

  "./components/mockups/landing/Editorial": () =>
    import("../components/mockups/landing/Editorial"),

  "./components/mockups/landing/ModernLight": () =>
    import("../components/mockups/landing/ModernLight"),

  "./components/mockups/landing/PremiumDark": () =>
    import("../components/mockups/landing/PremiumDark"),

  "./components/mockups/landing/SplitScreen": () =>
    import("../components/mockups/landing/SplitScreen"),

  "./components/mockups/landing/VibrantColor": () =>
    import("../components/mockups/landing/VibrantColor")
};
