// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing/AppStyle.tsx": () => import("../components/mockups/landing/AppStyle.tsx"),
  "./components/mockups/landing/Editorial.tsx": () => import("../components/mockups/landing/Editorial.tsx"),
  "./components/mockups/landing/ModernLight.tsx": () => import("../components/mockups/landing/ModernLight.tsx"),
  "./components/mockups/landing/PremiumDark.tsx": () => import("../components/mockups/landing/PremiumDark.tsx"),
  "./components/mockups/landing/SplitScreen.tsx": () => import("../components/mockups/landing/SplitScreen.tsx"),
  "./components/mockups/landing/VibrantColor.tsx": () => import("../components/mockups/landing/VibrantColor.tsx")
};
